### PR TITLE
Bugfix: Mail command failed: 421 Error: too many unauthenticated commands

### PR DESCRIPTION
**Pull request by sourabh8003**
This PR will fix the issue of too many unauthenticated commands while sending emails through automated test cases.

### CODE REVIEW

**Comment by jcdelmas** [comment]
Thank you for your PR.

Are you sure that a startup option is necessary to solve this issue ?

I think that `maxAllowedUnauthenticatedCommands` attribute can just be set to a big value (disabling does not seem well supported).

**Comment by sourabh8003** [comment]
@jcdelmas : No, startup option is not necessary to solve the issue but if we can pass the attribute value for `maxAllowedUnauthenticatedCommands` from the startup commands instead of hard coded value that will allow us to pass our own numbers to allowed commands.

**Comment by jcdelmas** [comment]
Ok, but I'd rather keep this project as simple as possible. So, if there is not a clear use case for adding this option, I'd rather have the value hard coded.

**Comment by sourabh8003** [comment]
@jcdelmas : That's fine, I'll update my PR. Thanks!

**Pull request merged**
